<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
فروش شکلات
</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در این گام از پروژه قصد داریم برای شکلات‌ها با توجه به برخی مشخصات‌شان و تحقیق‌هایی که کرده‌ایم قیمت تعیین کنیم. برای این کار از داده‌هایی که در گام قبل پردازش کرده‌ایم استفاده کرده و سپس مرحله به مرحله سعی می‌کنیم تخمین قیمت خود را بهتر کنیم.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در گام پیشین پروژه یک سری پیش‌پردازش‌هایی روی مجموعه‌داده‌ی شکلات‌ها انجام داده و حاصل را در فایل <code>chocolate_preprocessed.csv</code> ذخیره کردید. بنابراین ابتدا در سلول زیر این فایل را به شکل یک دیتافریم بخوانید.
</font>
</p>

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('chocolate_preprocessed.csv')
df.head()

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin
0,A. Morin,Agua Grande,2016,63.0,France,3.75,Blend,Sao Tome
1,A. Morin,Kpime,2015,70.0,France,2.75,Blend,Togo
2,A. Morin,Atsane,2015,70.0,France,3.00,Blend,Togo
3,A. Morin,Akata,2015,70.0,France,3.50,Blend,Togo
4,A. Morin,Quilla,2015,70.0,France,3.50,Blend,Peru

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت اول
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
فرض کنید که بعد از کمی تحقیق متوجه شده‌ایم که قیمت یک شکلات با درصد امتیاز آن توسط متخصصان رابطه‌ی مستقیم دارد. خوشبختانه این امتیاز در مشخصات داده‌های ما وجود دارد، اما مسئله این است که این امتیازها به‌صورت درصد نیستند. پس در این مرحله از شما می‌خواهیم تا مقادیر ستون <code>Rating</code> را به گونه‌ای تغییر مقیاس دهید که بالاترین مقدار آن ۱۰۰ باشد و سایر مقادیر نیز دقیقاً به همان نسبت تغییر کنند. به‌عنوان مثال فرض کنید بیشترین مقداری که در این ستون وجود دارد برابر ۴ باشد. در این‌صورت برای تبدیل ۴ به ۱۰۰ باید آن را ضرب در ۲۵ کنید. پس تمام مقادیر این ستون باید ضرب در ۲۵ شوند. توجه داشته باشید که در نهایت نوع ستون شما باید <code>float</code> باشد.
</font>
</p>

In [3]:
max=100/(df['Rating'].max())
df['Rating'] = df['Rating']*max
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1795 entries, 0 to 1794
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Company               1795 non-null   object
 1   Specific Bean Origin  1795 non-null   object
 2   Review Date           1795 non-null   int64
 3   Cocoa Percent         1795 non-null   float64
 4   Company Location      1795 non-null   object
 5   Rating                1795 non-null   float64
 6   Bean Type             1795 non-null   object
 7   Broad Bean Origin     1794 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 112.3+ KB

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت دوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
بعد از کمی تحقیق مشخص شد که قیمت ۱۰۰ گرم کاکائوی خالص با بالاترین کیفیت ۲۵۰۰۰۰ تومان است. بنابراین می‌توانیم با ضرب درصد کاکائو (ستون <code>Cocoa Percent</code>) در قیمت صد گرم آن (عدد ۲۵) و همچنین درصد امتیاز (ستون <code>Rating</code>)،‌ قیمت صد گرم از یک نوع شکلات را تخمین بزنیم.
در این قسمت به کمک فرمول زیر قیمت صد گرم از  هر نوع شکلات را محاسبه کرده و در ستون جدیدی به نام <code>price(100g)</code> ذخیره کنید.
<br>
<center>
قیمت صد گرم = درصد کاکائو × امتیاز × ۲۵
</center>
</font>
</p>

In [4]:
df['price(100g)'] = df['Cocoa Percent']*df['Rating']*25
df

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo,96250.0
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo,105000.0
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo,122500.0
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru,122500.0
...,...,...,...,...,...,...,...,...,...
1790,Zotter,Peru,2011,70.0,Austria,75.0,Blend,Peru,131250.0
1791,Zotter,Congo,2011,65.0,Austria,60.0,Forastero,Congo,97500.0
1792,Zotter,Kerala State,2011,65.0,Austria,70.0,Forastero,India,113750.0
1793,Zotter,Kerala State,2011,62.0,Austria,65.0,Blend,India,100750.0
1794,Zotter,"Brazil, Mitzi Blue",2010,65.0,Austria,60.0,Blend,Brazil,97500.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت سوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
فرض کنید که متوجه شده‌ایم شکلات‌های تلخ گران‌تر و پرسودتر هستند. بنابراین قصد داریم ادامه‌ی تمرین را تنها با این نوع از شکلات‌ها پیش ببریم.
در این قسمت شکلات‌هایی که درصد کاکائو آن‌ها بیشتر از ۷۰ درصد است را به‌عنوان شکلات تلخ در نظر گرفته و در مجموعه‌داده‌ی جدیدی با نام <code>dark_chocolates</code> ذخیره کنید.
</font>
</p>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
بعد از جداسازی و ساخت دیتافریم، به کمک تابع <code dir=ltr>reset_index()</code> نمایه‌ها را ریست کنید. در این مرحله به آرگومان‌های <code>inplace</code> و <code>drop</code> هم توجه کنید.
</font>
</p>

In [5]:
dark_chocolates = df[df.Rating>70]
dark_chocolates.reset_index()
dark_chocolates

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
8,A. Morin,Puerto Cabello,2014,70.0,France,75.0,Criollo,Venezuela,131250.0
9,A. Morin,Pablino,2014,70.0,France,80.0,Blend,Peru,140000.0
13,A. Morin,Equateur,2013,70.0,France,75.0,Blend,Ecuador,131250.0
17,A. Morin,Chuao,2013,70.0,France,80.0,Trinitario,Venezuela,140000.0
...,...,...,...,...,...,...,...,...,...
1773,Zokoko,Guadalcanal,2016,78.0,Australia,75.0,Blend,Solomon Islands,146250.0
1777,Zokoko,"Tranquilidad, Baures",2011,72.0,Australia,75.0,Blend,Bolivia,135000.0
1783,Zotter,"Loma Los Pinos, Yacao region, D.R.",2012,62.0,Austria,75.0,Blend,Dominican Republic,116250.0
1787,Zotter,Santo Domingo,2012,70.0,Austria,75.0,Blend,Dominican Republic,131250.0
1790,Zotter,Peru,2011,70.0,Austria,75.0,Blend,Peru,131250.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت چهارم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
نوع دانه‌ی استفاده شده برای ساخت شکلات نیز در مرغوبیت آن تاثیر مستقیم می‌گذارد. برای مثال یکی از بهترین دانه‌های شکلات از نوع <code>Trinitario</code> است.
به همین دلیل تصمیم گرفته‌ایم قیمت شکلات‌های تلخی (دیتافریم <code>dark_chocolates</code>) که از این دانه استفاده کرده‌اند را ۱۰ درصد افزایش دهیم.
<br>
ابتدا در متغیر <code>has_Trinitario</code> برای هر شکلات مشخص کنید که آیا در نام دانه‌های مختلف این شکلات (ستون <code>Bean Type</code>) اسمی از <code>Trinitario</code> برده شده است یا خیر. یعنی خروجی شما باید به شکل یک آرایه به طول دیتافریم شکلات‌های تلخ باشد که با توجه به وجود یا عدم وجود این نوع دانه در آن شکلات مقدار <code>True</code> یا <code>False</code> داشته باشد.
</font>
</p>

In [7]:
has_Trinitario = df['Bean Type'].str.contains('Trinitrario')
has_Trinitario.head()

0    False
1    False
2    False
3    False
4    False
Name: Bean Type, dtype: bool

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
اکنون می‌توانید از آرایه‌ی <code>has_Trinitario</code> استفاده کرده و قیمت آن ردیف‌هایی که در این آرایه مقدار <code>True</code> دارند را ۱۰ درصد افزایش دهید.
</font>
</p>

In [8]:
df.loc[has_Trinitario,'price(100g)']=df.loc[has_Trinitario,'price(100g)']*1.1
df.head()

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo,96250.0
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo,105000.0
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo,122500.0
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru,122500.0

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت پنجم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در مرحله‌ی آخر می‌خواهیم بدانیم در مجموع از فروش این شکلات‌های تلخ با قیمت‌هایی که مشخص کرده‌ایم چه‌قدر دریافت می‌کنیم. بنابراین مجموع قیمت شکلات‌های تلخ (ستون <code>price(100g)</code>) را محاسبه کرده و در متغیر <code>priceSum</code> ذخیره کنید.
</font>
</p>

In [9]:
df.to_csv('chocolet_price.csv')
priceSum = dark_chocolates['price(100g)'].sum()
priceSum

np.float64(42125187.5)